# CUSTOM CONF FILE

# LOCATIONS
# WINDOWS LOCAL
# RUBI_ICECAST_PLAYLIST_FILE='c:/rubi/playlist.log'
# LULA LINUX
RUBI_ICECAST_PLAYLIST_FILE = '/var/log/icecast2/playlist.log'

MAX_PLAYLIST_HISTORY_SIZE = 10
MAX_SUGGESTIONS_AUTO_SIZE = 20
