# Generated by Django 3.2.5 on 2021-12-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='energy',
        ),
    ]
