# Generated by Django 3.2.5 on 2021-12-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_remove_track_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='energy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
