# Generated by Django 5.2.6 on 2025-10-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0004_merge_20250930_1545"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="default_bmp_range_suggestions",
            field=models.IntegerField(
                default=3, help_text="Default BPM range for suggestions slider (%)"
            ),
        ),
    ]
