# Generated by Django 5.2.6 on 2025-10-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0005_add_bmp_range_suggestions_config"),
    ]

    operations = [
        migrations.RenameField(
            model_name="config",
            old_name="default_bmp_range_suggestions",
            new_name="default_bpm_range_suggestions",
        ),
    ]
