# Generated by Django 5.2.6 on 2025-10-02 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0006_rename_bmp_to_bpm"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuePoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        help_text="Position in track (e.g., '3:28')", max_length=10
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="Type of cue point",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Comment for this cue point",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cue Point",
                "verbose_name_plural": "Cue Points",
                "ordering": ["time"],
            },
        ),
        migrations.CreateModel(
            name="TrackCuePoints",
            fields=[
                (
                    "track",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="cue_points",
                        serialize=False,
                        to="track.track",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cue_point_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="track_cue_1",
                        to="track.cuepoint",
                    ),
                ),
                (
                    "cue_point_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="track_cue_2",
                        to="track.cuepoint",
                    ),
                ),
                (
                    "cue_point_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="track_cue_3",
                        to="track.cuepoint",
                    ),
                ),
                (
                    "cue_point_4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="track_cue_4",
                        to="track.cuepoint",
                    ),
                ),
                (
                    "cue_point_5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="track_cue_5",
                        to="track.cuepoint",
                    ),
                ),
                (
                    "cue_point_6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="track_cue_6",
                        to="track.cuepoint",
                    ),
                ),
                (
                    "cue_point_7",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="track_cue_7",
                        to="track.cuepoint",
                    ),
                ),
                (
                    "cue_point_8",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="track_cue_8",
                        to="track.cuepoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Track Cue Points",
                "verbose_name_plural": "Track Cue Points",
            },
        ),
    ]
