# Generated by Django 5.2.6 on 2025-10-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0007_cuepoint_trackcuepoints"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="default_musical_key_distance",
            field=models.IntegerField(
                default=3,
                help_text="Default musical key distance for suggestions slider",
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="default_ranking_min",
            field=models.IntegerField(
                default=4, help_text="Default minimum ranking for suggestions slider"
            ),
        ),
    ]
