# Generated by Django 5.2.6 on 2025-10-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0008_config_default_musical_key_distance_and_more"),
    ]

    operations = []
