# Generated by Django 5.2.6 on 2025-10-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0009_auto_20251002_1536"),
    ]

    operations = [
        migrations.CreateModel(
            name="MusicalKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "musical",
                    models.CharField(
                        help_text="Notation musicale traditionnelle, ex: Am",
                        max_length=8,
                        unique=True,
                    ),
                ),
                (
                    "camelot",
                    models.CharField(
                        help_text="Notation Camelot, ex: 8A", max_length=4, unique=True
                    ),
                ),
                (
                    "open",
                    models.CharField(
                        help_text="Notation Open Key, ex: 1m", max_length=4, unique=True
                    ),
                ),
                (
                    "traktor_color",
                    models.CharField(
                        help_text="Couleur Traktor (hex ou nom)", max_length=16
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Ordre pour le tri Traktor/Camelot"
                    ),
                ),
            ],
            options={
                "verbose_name": "Musical Key",
                "verbose_name_plural": "Musical Keys",
                "ordering": ["order"],
            },
        ),
    ]
