# Generated by Django 5.2.6 on 2025-10-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0010_musicalkey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="default_ranking_min",
            field=models.IntegerField(
                default=3, help_text="Default minimum ranking for suggestions slider"
            ),
        ),
    ]
