# Generated by Django 5.2.6 on 2025-10-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0012_remove_playlist_description_playlist_rank_and_more"),
    ]

    operations = []
