# Generated by Django 5.2.6 on 2025-10-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0013_sync_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="rank",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playlist",
            name="track_ids",
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="audio_id",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="file_path",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="location_dir",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
