# Generated by Django 5.2.6 on 2025-10-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0014_playlist_rank_playlist_track_ids_track_audio_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="currently_bpm_range_suggestions",
            field=models.IntegerField(
                default=3, help_text="BPM range (%) for currently playing suggestions"
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="currently_musical_key_distance",
            field=models.IntegerField(
                default=4,
                help_text="Musical key max distance for currently playing suggestions",
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="currently_ranking_min",
            field=models.IntegerField(
                default=1, help_text="Minimum ranking for currently playing suggestions"
            ),
        ),
    ]
