# Generated by Django 5.2.6 on 2025-11-03 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0015_config_currently_bpm_range_suggestions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="collection",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="track.collection",
            ),
            preserve_default=False,
        ),
    ]
