# Generated by Django 5.2.6 on 2025-11-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0016_playlist_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
