# Generated by Django 5.2.6 on 2025-11-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0017_alter_collection_name"),
    ]

    operations = []
