# Generated by Django 5.2.6 on 2025-11-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0019_add_config_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuepoint",
            name="duration",
            field=models.FloatField(
                blank=True, help_text="Duration in seconds for loops", null=True
            ),
        ),
        migrations.AddField(
            model_name="cuepoint",
            name="end_time",
            field=models.CharField(
                blank=True,
                help_text="End position for loops (e.g., '3:35')",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cuepoint",
            name="traktor_type",
            field=models.CharField(
                blank=True,
                help_text="Traktor TYPE field (0=cue, 4=loop, etc.)",
                max_length=10,
                null=True,
            ),
        ),
    ]
