# Generated by Django 5.2.6 on 2025-12-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0020_cuepoint_duration_cuepoint_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuepoint",
            name="len_ms",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cuepoint",
            name="time_ms",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuepoint",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuepoint",
            name="end_time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="cuepoint",
            name="time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="cuepoint",
            name="traktor_type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
