# Generated by Django 5.2.6 on 2025-12-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0021_cuepoint_len_ms_cuepoint_time_ms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuepoint",
            name="len_ms",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cuepoint",
            name="time_ms",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=16, null=True
            ),
        ),
    ]
