# Generated by Django 5.2.6 on 2026-02-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0022_alter_cuepoint_len_ms_alter_cuepoint_time_ms"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="default_playlist_favourites",
            field=models.CharField(
                default="634;611;621;616;630",
                help_text="Default favourite playlist IDs (semicolon-separated)",
                max_length=500,
            ),
        ),
    ]
