# Generated by Django 5.2.15 on 2026-07-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0023_add_default_playlist_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='separator_track_id',
            field=models.IntegerField(default=14294, help_text='ID of the separator track used to split playlists (instance-specific)'),
        ),
    ]
