# Generated by Django 5.2.15 on 2026-07-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0025_cuepoint_relational'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='playtime',
            field=models.FloatField(blank=True, help_text='Durée en secondes (PLAYTIME Traktor)', null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_id',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='file_path',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
