# Generated by Django 5.2.15 on 2026-07-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0027_playlisttrack_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlisttrack',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
