# Generated by Django 5.2.15 on 2026-07-03 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0028_alter_playlisttrack_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_track_id', models.IntegerField()),
                ('deleted_snapshot', models.JSONField(help_text='Champs de la track supprimée + cues + ids transitions/playlists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survivor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_logs', to='track.track')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='0-100, 100 = certitude (audio_id/file_path)')),
                ('reasons', models.JSONField(default=list, help_text="Raisons du match, ex: ['same_audio_id', 'fuzzy:93']")),
                ('cue_conflict', models.BooleanField(default=False, help_text='Les DEUX tracks ont des cue points')),
                ('status', models.CharField(choices=[('pending', 'À traiter'), ('merged', 'Fusionné'), ('dismissed', 'Pas un doublon')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_as_a', to='track.track')),
                ('track_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_as_b', to='track.track')),
            ],
            options={
                'ordering': ['-score', 'id'],
                'indexes': [models.Index(fields=['status', '-score'], name='track_dupcand_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('track_a', 'track_b'), name='unique_duplicate_pair')],
            },
        ),
    ]
