# Generated by Django 5.2.15 on 2026-07-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0030_populate_musical_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='play_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
