# Generated by Django 5.2.15 on 2026-07-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0031_transition_play_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='overlay_max_transitions',
            field=models.IntegerField(default=8, help_text="Nombre max de transitions affichées dans l'overlay (complétées par les 'Generated from Playlist' si moins)"),
        ),
    ]
